name: OptML2023
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - numpy
  - matplotlib
  - ipython
  - pylint
  - black
  - mypy
  - notebook
  - jupyter
  - scikit-learn
  - tqdm
  - pytorch
  - pandas
  - torchvision
